In [1]:
import pandas as pd
from bs4 import BeautifulSoup
import requests
import re
import datetime

In [2]:
n_pages = 0
a  =[]

for page in range(0,30):
    n_pages += 1
    url = 'https://www.zoopla.co.uk/for-sale/property/erdington/?identifier=erdington&page_size=10&q=erdington&search_source=home&radius=0&pn='+str(page)
    
    r = requests.get(url)
    data = r.text
    soup = BeautifulSoup(data)

    for link in soup.find_all('a'):
        a.append(link.get('href'))
        A = pd.DataFrame(a,columns=['text'])
        B = A[A.text.str.contains('for-sale/details') == True]

        B = B[B.text.str.contains('image') == False]
        B = B[B.text.str.contains('movie') == False]
        B = B.text.str.replace('/for-sale/details/','')
        C = B.unique()
    print(datetime.datetime.now())

    
print("Liekam jaunu bildi iek코캐!!!!")

2020-11-11 22:00:57.952409
2020-11-11 22:01:00.162915
2020-11-11 22:01:02.598728
2020-11-11 22:01:05.151359
2020-11-11 22:01:08.109348
2020-11-11 22:01:11.162449
2020-11-11 22:01:14.202039
2020-11-11 22:01:17.584778
2020-11-11 22:01:20.928104
2020-11-11 22:01:24.455786
2020-11-11 22:01:28.133950
2020-11-11 22:01:32.130702
2020-11-11 22:01:36.337204
2020-11-11 22:01:41.038143
2020-11-11 22:01:45.478805
2020-11-11 22:01:50.047301
2020-11-11 22:01:55.221376
2020-11-11 22:02:00.490694
2020-11-11 22:02:05.550145
2020-11-11 22:02:11.096952
2020-11-11 22:02:32.231639
2020-11-11 22:02:36.271314
2020-11-11 22:02:40.268601
2020-11-11 22:02:44.322724
2020-11-11 22:02:48.286444
2020-11-11 22:02:52.393277
2020-11-11 22:02:56.758320
2020-11-11 22:03:00.997725
2020-11-11 22:03:05.403833
2020-11-11 22:03:09.871212
Liekam jaunu bildi iek코캐!!!!

In [3]:
for thing in C:
    web = "https://www.zoopla.co.uk/for-sale/details/" + C

In [4]:
listing_id = []
beds = []
baths = []
prices = []
listings_category = []
property_type = []
member_type = []
listing_condition =[]

has_floorplan = []
is_retirement_home = []
is_shared_ownership =[]
num_images = []
price_qualifier =[]

closest_train_station = []
closest_school = []


for thing2 in web:
    r = requests.get(thing2)
    data = r.text
    soup2 = BeautifulSoup(data)
    
    #for thing in soup2:

    listx = str(re.findall("listing_id: .*$",soup2.select('script')[3].prettify(),re.MULTILINE))
    listing_id.append(int(listx[14:-3]))

    price = str(re.findall("price: .*$",soup2.select('script')[3].prettify(),re.MULTILINE))
    prices.append(float(price[9:-3]))
    
    bed = str(re.findall("num_beds: .*$",soup2.select('script')[3].prettify(),re.MULTILINE))
    beds.append(bed[12:-3])

    bath = str(re.findall("num_baths: .*$",soup2.select('script')[3].prettify(),re.MULTILINE))
    baths.append(bath[13:-3])

    category = str(re.findall("listings_category: .*$",soup2.select('script')[3].prettify(),re.MULTILINE))
    listings_category.append(category[22:-4])

    typex = str(re.findall("property_type: .*$",soup2.select('script')[3].prettify(),re.MULTILINE))
    property_type.append(typex[18:-4])
    
    memb = str(re.findall("member_type: .*$",soup2.select('script')[3].prettify(),re.MULTILINE))
    member_type.append(memb[16:-4])
    
    cond = str(re.findall("listing_condition: .*$",soup2.select('script')[3].prettify(),re.MULTILINE))
    listing_condition.append(cond[22:-4])
    
    floor = str(re.findall("has_floorplan: .*$",soup2.select('script')[3].prettify(),re.MULTILINE))
    has_floorplan.append(floor[17:-3])

    retire = str(re.findall("is_retirement_home: .*$",soup2.select('script')[3].prettify(),re.MULTILINE))
    is_retirement_home.append(retire[22:-3])    
    
    share = str(re.findall("is_shared_ownership: .*$",soup2.select('script')[3].prettify(),re.MULTILINE))
    is_shared_ownership.append(share[23:-3])

    picture = str(re.findall("num_images: .*$",soup2.select('script')[3].prettify(),re.MULTILINE))
    num_images.append(int(picture[14:-3]))

    money = str(re.findall("price_qualifier: .*$",soup2.select('script')[3].prettify(),re.MULTILINE))
    price_qualifier.append(money[20:-4])
    
    trains = str(soup2.select('.ui-local-amenities__distance')[1])[43:-13]
    closest_train_station.append(float(trains))
    
    school = str(soup2.select('.ui-local-amenities__distance')[3])[43:-13]
    closest_school.append(float(school))

In [5]:
cols = ['listing_id' ,'beds' ,'baths' ,'prices' ,'listings_category' ,'property_type' 
        ,'member_type' ,'listing_condition' ,'has_floorplan' ,'is_retirement_home' 
        ,'is_shared_ownership' ,'num_images' ,'price_qualifier', 'closest_train_station'
        , 'closest_school'
    
       ]

df = pd.DataFrame({'listing_id': listing_id
                    ,'beds': beds
                    ,'baths': baths
                    ,'prices': prices
                    ,'listings_category': listings_category
                    ,'property_type': property_type
                    ,'member_type': member_type
                    ,'listing_condition': listing_condition
                    ,'has_floorplan': has_floorplan
                    ,'is_retirement_home': is_retirement_home
                    ,'is_shared_ownership': is_shared_ownership
                    ,'num_images': num_images
                    ,'price_qualifier': price_qualifier
                    ,'closest_train_station' : closest_train_station
                    ,'closest_school' :  closest_school
                   
    
                   })[cols]

df.head()

,listing_id,beds,baths,prices,listings_category,property_type,member_type,listing_condition,has_floorplan,is_retirement_home,is_shared_ownership,num_images,price_qualifier,closest_train_station,closest_school
0,56910456,2,1,94950.0,residential,flat,agent,pre-owned,true,false,false,16,offers_in_region_of,0.8,0.3
1,56909708,3,1,235000.0,residential,semi_detached,agent,pre-owned,true,false,false,28,offers_in_region_of,0.6,0.4
2,56909347,2,1,52500.0,residential,maisonette,agent,pre-owned,true,true,true,14,,1.3,0.5
3,56907319,2,1,56000.0,residential,,agent,pre-owned,true,true,true,14,,0.7,0.4
4,56905429,2,1,175000.0,residential,semi_detached,agent,pre-owned,true,false,false,18,,1.7,0.3

In [6]:
def truefalse(x):
    if str.lower(str(x)) == "true":
        return (1)
    else:
        return (0)

In [7]:
df.has_floorplan = df.has_floorplan.apply(truefalse)
df.is_retirement_home = df.is_retirement_home.apply(truefalse)
df.is_shared_ownership = df.is_shared_ownership.apply(truefalse)
df.beds = df.beds*1
df.baths = df.baths*1
df.closest_school = df.closest_school*1
df.closest_train_station = df.closest_train_station*1

In [8]:
df.to_excel("Zoopla"+str(datetime.datetime.now().strftime("%Y%m%d"))+ ".xlsx")